<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Admin Panel - Carousel</title>
        <?php require("../admin/inc/links.php"); ?>
    </head>

    <body class="bg-light">

        <?php require("../admin/inc/header.php"); ?>
        
        <div class="container-fluid" id="main-content">
            <div class="row">
                <div class="col-lg-10 ms-3 p-3 overflow-hidden">
                    <h3 class="mb-4">CAROUSEL</h3>

                    
                    <!-- Carousel Section Starts -->
                    <div class="card border-0 shadow-sm mb-4 h-100">
                        <div class="card-body">
                            <div class="d-flex align-items-center justify-content-between mb-3">
                                <h5 class="card-title m-0">Images</h5>
                                <button type="button" class="btn btn-dark shadow-none btn-sm" data-bs-toggle="modal" data-bs-target="#carousel-s">
                                    <i class="bi bi-plus-square"></i> Add
                                </button>
                            </div>
                            
                            <div class="row d-flex" id="carousel-data" style="width: auto;">
                                <!-- Automatically generated by the code from the carousel_members session's on carousel_crud.php and data coming from the team_details table on the db -->
                            </div>
                            
                        </div>
                    </div>
                    <!-- Carousel section Ends -->


                    <!-- Carousel Modal Section Starts -->
                    <div class="modal fade" id="carousel-s" data-bs-backdrop="static" data-bs-keyboard="true" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <form id="carousel_s_form">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title">Add Image</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="mb-3">
                                            <label class="form-label fw-bold" for="carousel_picture_inp">Picture</label>
                                            <input type="file" name="carousel_picture" id="carousel_picture_inp" accept="[.jpg, .png, .webp, .jpeg]" class="form-control shadow-none" required>
                                            
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" onclick="carousel_picture.value=''" class="btn text-secondary shadow-none" data-bs-dismiss="modal">CANCEL</button>
                                        <button type="submit" class="btn custom-bg btn-outline-dark shadow-none">SUBMIT</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>  
                    <!-- Carousel Modal Section Ends -->
                    
                </div>    
            </div>
        </div>

        <?php require('inc/scripts.php'); ?>
        <script src="scripts/carousel.js"></script>
                
    </body>
</html>










